# Site settings
title: Musings of a programmer
description: Programmer. Photographer. Beer Aficianado
github_username:  kirankoduru
author: Kiran Koduru
paginate : 5

paginate_path: "/:num/"

url: http://kirankoduru.github.io
baseurl: http://kirankoduru.github.io

# Outputtin
permalink: /:categories/:title.html

# Build settings
markdown: kramdown

kramdown:
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-last-modified-at