# Site settings
title: Kiran Koduru
description: > # this means to ignore newlines until "baseurl:"
  Programmer. Photographer. Beer Aficianado
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  kirankoduru

# Build settings
markdown: kramdown

kramdown:
  input: GFM