# Site settings
title: Kiran Koduru
description: Programmer. Photographer. Beer Aficianado
github_username:  kirankoduru
paginate : 10

url: http://kirankoduru.github.io
baseurl: http://kirankoduru.github.io

# Outputtin
permalink: /:categories/:title.html

# Build settings
markdown: kramdown

kramdown:
  input: GFM

gems:
  - jekyll-sitemap